### ISSUE TITLE
SUPEE-8788 - 1.9.3.1

### ISSUE THREAD

**Issue by rob3000** [mercator/mercator#16]
Hey Guys, 

Wondering what the process is around patching for the latest vulnerabilities (8788) included in the 1.9.3.1 release. Do you guys have a schedule for when this would be released? Happy to merge back if there is a process around how to patch.

**Comment by chnorton** [comment]
Given there's some interest, we are actually already working on upgrading the codebase to the 1.9.3.1 version of Magento, which we expect to have finished soon. Appreciate the offer for assistance though, and anywhere else you might be able to contribute would be most welcome. In particular, the third-party extensions that are included with Mercator have not been updated for some time, and it would be fantastic if someone could help merge in and test the upstream changes for any of them.
